### ISSUE TITLE
Fehler bei der Ausgabe von Umlauten und Sonderzeichen

### ISSUE THREAD

**Issue by gregor-dev-443** [nimajneBG/password-generator#1]
Umlaute und Sonderzeichen werden nicht korrekt dargestellt!

**Comment by gregor-dev-443** [comment]
Unter Linux geht das aber nicht.
Ich guck mal nach einer anderen Möglichkeit mit locale.

**Comment by nimajneBG** [comment]
Müsste mit grafische Oberfläche funktionieren
